/*
 * ************* DO NOT EDIT THIS FILE ***********
 *
 * This file was automatically generated from IVpeResizer.idl.
 */

package org.jboss.tools.vpe.mozilla.internal.swt.xpl;

import org.jboss.tools.vpe.mozilla.internal.swt.xpl.XPCOMObject;


/**
 *
 * IID: 0xa78399a0-63c4-4deb-861a-1281ae87a4de
 */

public class VpeResizer extends nsISupports
{
	static final int LAST_METHOD_ID = nsISupports.LAST_METHOD_ID + 5;
	
    public static final String IVPERESIZER_IID_STRING =
        "c5673ccf-eb08-4cf4-b189-a674c6d3b4a2";

    public static final nsID IVPERESIZER_IID =
        new nsID(IVPERESIZER_IID_STRING);

    /* const short eTopLeft = 1; */
    public static final short eTopLeft = 1;

    /* const short eTop = 2; */
    public static final short eTop = 2;

    /* const short eTopRight = 4; */
    public static final short eTopRight = 4;

    /* const short eLeft = 8; */
    public static final short eLeft = 8;

    /* const short eRight = 16; */
    public static final short eRight = 16;

    /* const short eBottomLeft = 32; */
    public static final short eBottomLeft = 32;

    /* const short eBottom = 64; */
    public static final short eBottom = 64;

    /* const short eBottomRight = 128; */
    public static final short eBottomRight = 128;
	
	private boolean isShow;
    public VpeResizer(int address) {
		super(address);
		isShow = false;
	}

	private int init(int aDOMDocument, int aPressShell) {
		return XPCOM.VtblCall(super.LAST_METHOD_ID + 1, getAddress(), aDOMDocument, aPressShell);
	}
	
	private int show(int aElement, int resizers) {
		return XPCOM.VtblCall(super.LAST_METHOD_ID + 2, getAddress(), aElement, resizers);
	}

	private int hide() {
		return XPCOM.VtblCall(super.LAST_METHOD_ID + 3, getAddress());
	}
	
	private int addResizeListener(int aListener) {
		return XPCOM.VtblCall(super.LAST_METHOD_ID + 4, getAddress(), aListener);
	}

	private int removeResizeListener(int aListener) {
		return XPCOM.VtblCall(super.LAST_METHOD_ID + 5, getAddress(), aListener);
	}

	/* void Init (in nsIDOMDocument aDOMDocument, in nsIPresShell aPresShell); */
    public void Init(nsIDOMDocument aDOMDocument, nsIPresShell aPresShell) {
		int rc = init(aDOMDocument.getAddress(), aPresShell.getAddress());
		if (rc != XPCOM.NS_OK) {
			error(rc);
		}
    }

    /* void Show (in nsIDOMElement aElement); */
    public void Show(nsIDOMElement aElement, int resizers) {
		if (isShow) {
			Hide();
		}

		if (!isShow) {
			int rc = show(aElement.getAddress(), resizers);
			if (rc != XPCOM.NS_OK) {
				error(rc);
			}
			isShow = true;
		}
    }

	public void Hide() {
		if(isShow) {
			int rc = hide();
			if (rc != XPCOM.NS_OK) {
				error(rc);
			}
			isShow = false;
		}
	}

	public void AddResizeListener(XPCOMObject aListener) {
		int rc = addResizeListener(aListener.getAddress());
		if (rc != XPCOM.NS_OK) {
			error(rc);
		}
	}

	public void RemoveResizeListener(XPCOMObject aListener) {
		int rc = removeResizeListener(aListener.getAddress());
		if (rc != XPCOM.NS_OK) {
			error(rc);
		}
	}
}

/*
 * end
 */
