#include "nsISupports.idl"

interface nsIDOMElement;

[scriptable,uuid(7E84CC02-D8E0-44fe-89CD-62A48B0CACE0)]

interface IVpeDropListener : nsISupports
{
  void CanDrop(in PRInt32 aClientX, in PRInt32 aClientY, in nsIDOMElement aElement, in nsIDOMElement aDropOnElement, out PRInt32 aResult);
  void Drop(in PRInt32 aClientX, in PRInt32 aClientY, in nsIDOMElement aElement);
};
