#include "nsISupports.idl"
%{C++
#include "nsAString.h"
%}

interface nsIDOMEvent;
interface nsIDOMNode;

[scriptable,uuid(7E84CC02-D8E0-44fe-89CD-62A48B0CACE0)]

interface IVpeDragDropListener : nsISupports
{
  void CanDrag(in nsIDOMEvent aDropEvent, out PRInt32 aResult, out nsIDOMNode aNode, out PRInt32 aOffcet);
  void CanDrop(in nsIDOMEvent aDropEvent, out PRInt32 aResult, out nsIDOMNode aNode, out PRInt32 aOffcet);
  void Drop(in nsIDOMEvent aDropEvent, out nsIDOMNode aNode, out PRInt32 aOffcet);
	
  void CanDropExternal(in nsIDOMEvent aDropEvent, in AString aFlavor, in AString aTransferData, out PRInt32 aResult, out nsIDOMNode aNode, out PRInt32 aOffcet);
  void DropExternal(in nsIDOMEvent aDropEvent, in AString aFlavor, in AString aTransferData, out nsIDOMNode aNode, out PRInt32 aOffcet);
};
