java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common_2.0.0.200709100004-nightly/common.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.gef_2.0.0.200709100004-nightly/common-gef.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.kb_2.0.0.200709100004-nightly/kb.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.model_2.0.0.200709100004-nightly/model.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.model.ui_2.0.0.200709100004-nightly/model_ui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.projecttemplates_2.0.0.200709100004-nightly/projtempl.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.text.ext_2.0.0.200709100004-nightly/texteditorextensions.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.text.xml_2.0.0.200709100004-nightly/xmleditor.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.verification_2.0.0.200709100004-nightly/verification.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.common.verification.ui_2.0.0.200709100004-nightly/verificationui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.jsp_2.0.0.200709100004-nightly/jspeditor.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web_2.0.0.200709100004-nightly/web.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web.debug_2.0.0.200709100004-nightly/debug.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web.debug.ui_2.0.0.200709100004-nightly/ui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web.tiles_2.0.0.200709100004-nightly/web-tiles.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web.tiles.ui_2.0.0.200709100004-nightly/tilesui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web.ui_2.0.0.200709100004-nightly/webui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jst.web.verification_2.0.0.200709100004-nightly/web-verification.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf_2.0.0.200709100004-nightly/jsf.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf.text.ext_2.0.0.200709100004-nightly/jsfextensions.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf.text.ext.facelets_2.0.0.200709100004-nightly/jsfextensions.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf.ui_2.0.0.200709100004-nightly/jsfui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf.verification_2.0.0.200709100004-nightly/jsf-verification.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf.vpe.facelets_2.0.0.200709100004-nightly/vpefacelets.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.jsf.vpe.tomahawk_2.0.0.200709100004-nightly/vpetomahawk.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.vpe_2.0.0.200709100004-nightly/vpe.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.vpe.mozilla.win32_2.0.0/mozilla-vpe.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.vpe.ui_2.0.0.200709100004-nightly/vpeproui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.vpe.ui.palette_2.0.0.200709100004-nightly/palettegef.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.seam.core_2.0.0.200709100004-nightly/seam-core.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.seam.ui_*.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.seam.xml_2.0.0.200709100004-nightly/seam-xml.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.seam.xml.ui_2.0.0.200709100004-nightly/seam-xml-ui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.struts_2.0.0/struts.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.struts.debug_2.0.0.200709100004-nightly/strutsdebug.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.struts.text.ext_2.0.0.200709100004-nightly/strutsextensions.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.struts.ui_2.0.0.200709100004-nightly/strutsui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.struts.validator.ui_2.0.0.200709100004-nightly/strutsvalidatorui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.struts.verification_2.0.0.200709100004-nightly/struts-verification.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.hibernate.ui.veditor/orm2-veditor.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.hibernate.ui.view/view.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.hibernate.xml/orm2-xml.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.hibernate.xml.ui/orm2-xml-ui.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.shale_2.0.0/shale.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.shale.text.ext_2.0.0.200709100004-nightly/shaleextensions.jar
java -classpath ./emma.jar emma instr -m overwrite -verbose -cp  ./rhds/eclipse/plugins/org.jboss.tools.shale.ui_2.0.0.200709100004-nightly/shaleui.jar