#include "nsISupports.idl"

interface nsIDOMDocument;
interface nsIPresShell;
interface nsIDOMElement;
interface nsIDOMEvent;
interface IVpeResizeListener;
interface nsIDOMWindow;

[scriptable,uuid(C5673CCF-EB08-4cf4-B189-A674C6D3B4A2)]

interface IVpeResizer : nsISupports
{
  const short eTopLeft = 1;
  const short eTop = 2;
  const short eTopRight = 4;
  const short eLeft = 8;
  const short eRight = 16;
  const short eBottomLeft = 32;	
  const short eBottom = 64;
  const short eBottomRight = 128;
  
  void Init(in nsIDOMDocument aDOMDocument, in nsIPresShell aPresShell);

  void Show(in nsIDOMElement aElement, in PRInt32 resizers);
  void Hide();
  void AddResizeListener(in IVpeResizeListener aListener);
  void RemoveResizeListener(in IVpeResizeListener aListener);
	
  void MouseDown(in PRInt32 aX, in PRInt32 aY, in nsIDOMElement target);
  void MouseMove(in nsIDOMEvent event);	
  void MouseUp(in PRInt32 aX, in PRInt32 aY, in nsIDOMElement target);
};
